In [3]:
import os
import pandas as pd

In [4]:
home_dir = os.path.expanduser('~')
print(home_dir)

/Users/ujaval

In [9]:
filename = 'cities5000.txt'
folder = 'Downloads/python_geospatial/'
path = os.path.join(home_dir, folder, filename)
print(path)

/Users/ujaval/Downloads/python_geospatial/cities5000.txt

In [32]:
column_names = ['geonameid', 'name', 'asciiname', 'alternatenames', 'latitude', 'longitude', 'feature class', 'feature code', 'country code', 'cc2', 'admin1 code', 'admin2 code', 'admin3 code', 'admin4 code', 'population', 'elevation', 'dem', 'timezone', 'modification date']
df = pd.read_csv(path, sep='\t', names=column_names)
df.head()

,geonameid,name,asciiname,alternatenames,latitude,longitude,feature class,feature code,country code,cc2,admin1 code,admin2 code,admin3 code,admin4 code,population,elevation,dem,timezone,modification date
0,3039163,Sant Julià de Lòria,Sant Julia de Loria,"San Julia,San Julià,Sant Julia de Loria,Sant J...",42.46372,1.49129,P,PPLA,AD,NaN,06,NaN,NaN,NaN,8022,NaN,921,Europe/Andorra,2013-11-23
1,3039678,Ordino,Ordino,"Ordino,ao er di nuo,orudino jiao qu,Ордино,オルデ...",42.55623,1.53319,P,PPLA,AD,NaN,05,NaN,NaN,NaN,3066,NaN,1296,Europe/Andorra,2018-10-26
2,3040051,les Escaldes,les Escaldes,"Ehskal'des-Ehndzhordani,Escaldes,Escaldes-Engo...",42.50729,1.53414,P,PPLA,AD,NaN,08,NaN,NaN,NaN,15853,NaN,1033,Europe/Andorra,2008-10-15
3,3040132,la Massana,la Massana,"La Macana,La Massana,La Maçana,La-Massana,la M...",42.54499,1.51483,P,PPLA,AD,NaN,04,NaN,NaN,NaN,7211,NaN,1245,Europe/Andorra,2008-10-15
4,3040686,Encamp,Encamp,"Ehnkam,Encamp,en kan pu,enkanpu jiao qu,Энкам,...",42.53474,1.58014,P,PPLA,AD,NaN,03,NaN,NaN,NaN,11223,NaN,1257,Europe/Andorra,2018-10-26

In [33]:
df.shape

(50118, 19)

In [30]:
country = 'IN'
india_df = df[(df['country code']==country) & (df['population'] > 1000000)].copy()
india_df.shape

(41, 19)

In [19]:
%run ./distance.ipynb

In [31]:
india_df['distance'] = india_df.apply(lambda row: haversine_distance((77.56, 12.97), (row['longitude'], row['latitude'])), axis=1)
india_df['distance'] = india_df['distance'].apply(lambda x: '%.2f' % x)
display(india_df)

,geonameid,name,asciiname,alternatenames,latitude,longitude,feature class,feature code,country code,cc2,admin1 code,admin2 code,admin3 code,admin4 code,population,elevation,dem,timezone,modification date,distance
19928,1253102,Visakhapatnam,Visakhapatnam,"VTZ,Vaisakhapattanam,Vaisākhapattanam,Visak,Vi...",17.68009,83.20161,P,PPLA2,IN,NaN,02,544,NaN,NaN,1063178,NaN,24,Asia/Kolkata,2019-09-05,632.87
19971,1253405,Varanasi,Varanasi,"Banaras,Banares,Banāras,Benares,Benarés,Kashi,...",25.31668,83.01041,P,PPL,IN,NaN,36,197,NaN,NaN,1164404,NaN,86,Asia/Kolkata,2019-05-07,645.45
19988,1253573,Vadodara,Vadodara,"BDQ,Baroda,Vadodara,Vapadedara,ba luo da,badod...",22.29941,73.20812,P,PPL,IN,NaN,09,486,NaN,NaN,1409476,NaN,46,Asia/Kolkata,2014-10-13,548.69
20089,1254361,Tirunelveli,Tirunelveli,"Nellai,Tinnevelli,Tinnevelly,Tinnevelly Juncti...",8.72742,77.68380,P,PPLA2,IN,NaN,25,628,NaN,NaN,1435844,NaN,49,Asia/Kolkata,2017-08-27,102.04
20120,1254661,Thāne,Thane,"Tanja,Tanna,Thana,Thane,Thāna,Thāne,tanh,tany,...",19.19704,72.96355,P,PPL,IN,NaN,16,517,NaN,NaN,1261517,NaN,23,Asia/Kolkata,2019-03-29,539.90
20131,1254745,Teni,Teni,"Teni,Theni,Tkheni,Тхени",10.01115,77.47772,P,PPLX,IN,NaN,25,624,NaN,NaN,1034724,NaN,300,Asia/Kolkata,2017-08-02,71.68
20188,1255364,Surat,Surat,"STV,Surat,Suratas,Surate,Sūrat,su la te,surata...",21.19594,72.83023,P,PPL,IN,NaN,09,492,NaN,NaN,2894504,NaN,20,Asia/Kolkata,2020-04-04,574.26
20607,1258847,Rājkot,Rajkot,"RAJ,Radzhkot,Radzkot,Radzkotas,Radźkot,Radžkot...",22.29161,70.79322,P,PPL,IN,NaN,09,476,NaN,NaN,1177362,NaN,140,Asia/Kolkata,2017-03-17,801.44
20668,1259229,Pune,Pune,"PNQ,Pona,Poona,Poune,Pun,Puna,Pune,Puneo,Puno,...",18.51957,73.85535,P,PPL,IN,NaN,16,521,NaN,NaN,2935744,NaN,554,Asia/Kolkata,2015-06-04,438.75
20720,1259652,Pimpri,Pimpri,Pimpri,18.62292,73.80696,P,PPL,IN,NaN,16,521,NaN,NaN,1284606,NaN,571,Asia/Kolkata,2014-10-13,444.85
20779,1260086,Patna,Patna,"'Azimabad,New Patna,PAT,Patna,Patna New City,P...",25.59408,85.13563,P,PPLA,IN,NaN,34,230,NaN,NaN,1599920,NaN,53,Asia/Kolkata,2018-12-14,863.45
20901,1261162,Nowrangapur,Nowrangapur,"Nabarangapur,Nabarangpur,Nowrangpur",19.23114,82.54826,P,PPLA2,IN,NaN,21,397,NaN,NaN,1220946,NaN,578,Asia/Kolkata,2014-10-14,566.75
20963,1261731,Nashik,Nashik,"ISK,Nashik,Nasik,Nasikas,Nasiko,Naszik,Našikas...",19.99727,73.79096,P,PPLA2,IN,NaN,16,516,NaN,NaN,1289497,NaN,584,Asia/Kolkata,2014-10-13,460.81
21023,1262111,Najafgarh,Najafgarh,"Najafgarh,Najafgarli",28.60922,76.97982,P,PPL,IN,NaN,07,097,NaN,NaN,1365000,NaN,215,Asia/Kolkata,2019-07-18,387.38
21033,1262180,Nagpur,Nagpur,"Ajni,NAG,Nagpore,Nagpur,Nagpura,Nagpuras,Nankp...",21.14631,79.08491,P,PPLA2,IN,NaN,16,505,NaN,NaN,2228018,NaN,319,Asia/Kolkata,2019-10-22,249.83
21155,1263214,Meerut,Meerut,"Meerut,Meerut City,Merath,Meratkh,Mirat,Mirata...",28.98002,77.70636,P,PPL,IN,NaN,36,138,NaN,NaN,1223184,NaN,228,Asia/Kolkata,2015-05-06,380.43
21318,1264527,Chennai,Chennai,"Cenaj,Cenajo,Cenajus,Cenay,Cennai,Cennaj,Chehn...",13.08784,80.27847,P,PPLA,IN,NaN,25,603,NaN,NaN,4328063,NaN,14,Asia/Kolkata,2019-09-05,302.29
21339,1264728,Ludhiāna,Ludhiana,"LUH,Ludhiana,Ludhijana,Ludhiāna,Ludkhijana,lud...",30.91204,75.85379,P,PPL,IN,NaN,23,041,NaN,NaN,1545368,NaN,256,Asia/Kolkata,2017-03-07,493.92
21340,1264733,Lucknow,Lucknow,"LKO,Lakhnau,Lakkhnau,Lakkhnau shaary,Laknaou,L...",26.83928,80.92313,P,PPLA,IN,NaN,36,157,NaN,NaN,2472011,NaN,126,Asia/Kolkata,2015-11-11,469.40
21679,1267995,Kanpur,Kanpur,"Cawnpore,KNU,Kanpur,Kanpuras,Kanpwr,Kānpur,Kān...",26.46523,80.34975,P,PPL,IN,NaN,36,164,NaN,NaN,2823249,NaN,137,Asia/Kolkata,2015-08-08,420.97
21717,1268295,Kalyān,Kalyan,"Kal'jan,Kalyan,Kalyān,Кальян",19.24370,73.13554,P,PPL,IN,NaN,16,517,NaN,NaN,1262255,NaN,10,Asia/Kolkata,2014-10-13,521.97
21875,1269515,Jaipur,Jaipur,"Caypur,Dzaipur,Dzaipuras,Dzajpur,Dzajpura,Dzha...",26.91962,75.78781,P,PPLA,IN,NaN,24,110,NaN,NaN,2711758,NaN,435,Asia/Kolkata,2019-09-05,406.82
21893,1269633,Jabalpur,Jabalpur,"Dzabalpur,Dzabalpuras,Dzhabalpur,Dzsabalpur,Dż...",23.16697,79.95006,P,PPL,IN,NaN,35,451,NaN,NaN,1030168,NaN,416,Asia/Kolkata,2014-10-14,344.75
21907,1269743,Indore,Indore,"IDR,Indaur,Indor,Indore,Indore Madhya Pradesh,...",22.71792,75.83330,P,PPL,IN,NaN,35,439,NaN,NaN,1837041,NaN,550,Asia/Kolkata,2014-10-14,314.12
21924,1269843,Hyderabad,Hyderabad,"Bhaganagar,HYD,Haidarabadas,Haiderabad,Hajdara...",17.38405,78.45636,P,PPLA,IN,NaN,40,536,NaN,NaN,3597816,NaN,515,Asia/Kolkata,2014-10-10,142.53
21993,1270396,Hāora,Haora,"Haora,Haura,Hawrah,Howrah,Hāora,ha'ora,haura,হ...",22.57688,88.31857,P,PPL,IN,NaN,28,341,NaN,NaN,1027672,NaN,8,Asia/Kolkata,2014-10-14,1199.32
22063,1270926,Gorakhpur,Gorakhpur,"Gorakhpur,Gorakpura,Горакпура",29.44768,75.67206,P,PPL,IN,NaN,10,078,NaN,NaN,1324570,NaN,218,Asia/Kolkata,2017-09-05,471.06
22105,1271308,Ghāziābād,Ghaziabad,"Gaziabad,Ghaziabad,Ghazibad,Ghāziābād,Газиабад",28.66535,77.43915,P,PPLA2,IN,NaN,36,140,NaN,NaN,1199191,NaN,214,Asia/Kolkata,2018-07-13,376.86
22186,1271951,Faridabad,Faridabad,"Faridabad,Faridabadas,Farīdābād,QNF,faridabado...",28.41124,77.31316,P,PPL,IN,NaN,10,088,NaN,NaN,1220229,NaN,209,Asia/Kolkata,2017-05-06,373.40
22234,1272423,Dombivli,Dombivli,Dombivali,19.21667,73.08333,P,PPL,IN,NaN,16,517,NaN,NaN,1193000,NaN,11,Asia/Kolkata,2014-10-13,527.29
22333,1273294,Delhi,Delhi,"DEL,Daehli,Dehli,Dehlī,Delchi,Delhi,Delhio,Del...",28.65195,77.23149,P,PPLA,IN,NaN,07,NaN,NaN,NaN,10927986,NaN,227,Asia/Kolkata,2019-09-05,381.11
22512,1275004,Kolkāta,Kolkata,"CCU,Calcuta,Calcutta,Calcutá,Calcúta,Caligarda...",22.56263,88.36304,P,PPLA,IN,NaN,28,342,NaN,NaN,4631392,NaN,11,Asia/Kolkata,2020-04-08,1204.16
22534,1275339,Mumbai,Mumbai,"Asumumbay,BOM,Bombai,Bombaim,Bombaj,Bombay,Bom...",19.07283,72.88261,P,PPLA,IN,NaN,16,NaN,NaN,NaN,12691836,NaN,8,Asia/Kolkata,2019-09-05,547.46
22605,1275841,Bhopāl,Bhopal,"BHO,Bhojpal,Bhopal,Bhopala,Bhopalas,Bhopalo,Bh...",23.25469,77.40289,P,PPLA,IN,NaN,35,444,NaN,NaN,1599914,NaN,523,Asia/Kolkata,2020-04-08,248.18
22786,1277333,Bengaluru,Bengaluru,"BLR,Ban'nkalor,Bangalor,Bangalora,Bangalore,Ba...",12.97194,77.59369,P,PPLA,IN,NaN,19,572,NaN,NaN,5104047,920.0,914,Asia/Kolkata,2019-09-05,3.75
22886,1278149,Aurangabad,Aurangabad,"Aurangabad,Aurangabad - aurangabada,Aurangabad...",19.87757,75.34226,P,PPLA2,IN,NaN,16,515,NaN,NaN,1016441,NaN,588,Asia/Kolkata,2019-03-29,304.86
22967,1278710,Amritsar,Amritsar,"ATQ,Amricar,Amritsar,Amritsar - amritasara,Amr...",31.62234,74.87534,P,PPL,IN,NaN,23,049,NaN,NaN,1092450,NaN,244,Asia/Kolkata,2015-11-08,573.56
23013,1278994,Allahābād,Allahabad,"Alahabadas,Alla Abba Habab,Allahabad,Allahabad...",25.44478,81.84322,P,PPL,IN,NaN,36,175,NaN,NaN,1073438,NaN,99,Asia/Kolkata,2020-01-17,534.30
23054,1279233,Ahmedabad,Ahmedabad,"AMD,Achmentampant,Ahmadabad,Ahmadabadas,Ahmada...",23.02579,72.58727,P,PPL,IN,NaN,09,474,NaN,NaN,3719710,NaN,56,Asia/Kolkata,2019-09-05,621.49
23056,1279259,Agra,Agra,"AGR,Agra,Agra - agara,Agra - आगरा,Lungsod ng A...",27.18333,78.01667,P,PPLA2,IN,NaN,36,146,NaN,NaN,1430055,NaN,166,Asia/Kolkata,2016-10-17,337.27
23132,6619347,Navi Mumbai,Navi Mumbai,"Marathi Maharashtra,Navi Moembaai,Navi Mumbai...",19.03681,73.01582,P,PPLX,IN,NaN,16,517,NaN,NaN,2600000,NaN,14,Asia/Kolkata,2018-12-04,532.88

In [9]:
output = os.path.join(home_dir, 'Downloads', 'output.csv')
print(output)
india_df.to_csv(output, index=False)

/Users/ujaval/Downloads/output.csv